import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import Script from "next/script";
// import Dummy from "../../components/dummy";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* Styles for selected elements in a particular components */}
      <style jsx>
        {`
          .myspan {
            color: red;
          }
          .text {
            margin-top: 15px;
            font-weight: bold;
          }
        `}
      </style>
      <Head>
        <title>DevHunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <script src="sc.js" strategy="lazyOnload"></script> */}

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.custom}>
          {/* Testing my Style jsx a new way to style a particular component
          <span className="taha">Usama Rehan Farooqi</span>
          <span className="myspan">ARUSH</span>
          <Dummy /> */}
          <h1 className={styles.title}>DevHunter</h1>
          {/* <Image
            src="/homeImage.jpg"
            className={styles.homeImage}
            width={300}
            height={133}
            alt="This is a Home Image"
            priority={true}
          /> */}
          <img
            className={styles.homeImage}
            src="/homeImage.jpg"
            width={300}
            height={133}
            alt="This is a Home Image"
          />

          <p className="text">A blog for coders by a coder</p>

          <div className="blogs">
            <h2 className={styles.popularBlogs}>Latest Blogs</h2>
            <div className={styles.title}>
              <h3>How to learn Javascript in 2024</h3>
              <p>Javascript is language used for the web behaviour</p>
            </div>
            <div className={styles.title}>
              <h3>How to learn Javascript in 2024</h3>
              <p>Javascript is language used for the web behaviour</p>
            </div>
            <div className={styles.title}>
              <h3>How to learn Javascript in 2024</h3>
              <p>Javascript is language used for the web behaviour</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
